name: MGM240P Zigbee
device: MGM240PB32VNA
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{fw_variant}_{baudrate}"
sdk: "simplicity_sdk:2025.6.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: rcp_uart
  ot_rcp_version: dynamic
  ezsp_version: dynamic
  baudrate: 115200
  fw_variant: sw_flow

configuration:
  SL_STACK_SIZE: 2752
  SL_CPC_DRV_UART_VCOM_BAUDRATE: 115200
  SL_CPC_DRV_UART_VCOM_FLOW_CONTROL_TYPE: uartFlowControlSoftware
  OPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE: 0
  OPENTHREAD_CONFIG_LOG_OUTPUT: OPENTHREAD_CONFIG_LOG_OUTPUT_NONE
  OPENTHREAD_CONFIG_MULTIPAN_RCP_ENABLE: 1
  OPENTHREAD_CONFIG_MULTIPLE_INSTANCE_ENABLE: 1
  OPENTHREAD_CONFIG_MULTIPLE_STATIC_INSTANCE_ENABLE: 1
  OPENTHREAD_CONFIG_MAC_CSL_RECEIVER_ENABLE: 0
  OPENTHREAD_CONFIG_MAC_CSL_AUTO_SYNC_ENABLE: 0
  SL_CPC_RX_BUFFER_MAX_COUNT: 15
  SL_CPC_TX_QUEUE_ITEM_MAX_COUNT: 15
  CIRCULAR_QUEUE_LEN_MAX: 16
  ENABLE_ENCRYPTION: false
  SL_CPC_ENDPOINT_FLAG_DISABLE_ENCRYPTION: true
  SL_CPC_SECURITY_ENABLED: false

c_defines:
  SL_CPC_DRV_UART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_CPC_DRV_UART_VCOM_TX_PIN: 5

  SL_CPC_DRV_UART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_CPC_DRV_UART_VCOM_RX_PIN: 6

  SL_CPC_DRV_UART_VCOM_PERIPHERAL: USART0
  SL_CPC_DRV_UART_VCOM_PERIPHERAL_NO: 0

